title: "Deanne Tak On Wah"
author: "Deanne Wah"
description: "PhD Candidate at The University of Western Ontario"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "index.html"}
  - {title: "Publications", file: "publications.md"}
  - {title: "My Classroom", file: "virtualclassroom.html"}
  - {title: "Teaching Resources: to be added"}
  - {title: "Escape Rooms: to be added"}

avatar: "Deannepic.png"

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:dwah@uwo.ca"}
  - {title: Github, icon: github, url: "https://github.com/ddeannew"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/ddeannew"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
