title: "Deanne Tak On Wah"
author: "Deanne Wah"
description: "Deanne Tak On Wah | PhD Candidate at | The University of Western Ontario"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu
image:
  source: assets/images/
  output: generated
  presets:
    # Proportional preset
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 350
    # Scaled and cropped preset
    half:
      width: 400
      height: 400

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {% image {{ Deannepic.png }} alt="deanne" %}
  - {title: "Home", file: "index.html"}
  - {title: "Publications", file: "publications.md"}
  - {title: "My Classroom", file: "virtualclassroom.html"}
  - {title: "Teaching Resources: to be added"}
  - {title: "Escape Rooms: to be added"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:dwah@uwo.ca"}
  - {title: Github, icon: github, url: "https://github.com/ddeannew"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/ddeannew"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
